name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: "3.16.x"
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install libsdl2* -y
      - name: Configure and build
        run: |
            bash ./build.bash
      - name: Test
        run: |
          ./build/src/bullet_game -t
